version: '3'

services:
    app:
        container_name: RivagesPropres-app
        build:
            context: ./docker/php/
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - 8000:8000
        volumes:
            - ./RivagesPropres/:/var/www/
        networks:
            - RivagesPropres

    database:
        container_name: RivagesPropres-database
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: RivagesPropres
        ports:
            - 3306
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - RivagesPropres

    phpmyadmin:
        container_name: RivagesPropres-phpmyadmin
        image: phpmyadmin:latest
        restart: always
        ports:
            - 8001:80
        environment:
            - PMA_HOST=database
        networks:
            - RivagesPropres

volumes:
    db-data:

networks:
    RivagesPropres:
